apiVersion: 1

datasources:
  - name: AuraVault-CrateDB
    uid: auravault-crate
    type: postgres
    access: proxy
    url: crate-db:5432
    user: crate
    secureJsonData:
      password: ""
    jsonData:
      database: doc
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
      connMaxLifetime: 14400
      maxOpenConns: 100
      maxIdleConns: 100
      timeInterval: 5m
    isDefault: true
    editable: true
