"""Catalogo base de AuraVault con datos reales de centros, salas y obras.

Fuentes principales usadas para nombres e imagenes:
- MUNCYT / CERES / Wikimedia Commons
- Museo de Belas Artes da Coruna / Wikimedia Commons
- Teatro Rosalia de Castro (Wikipedia + Commons)
- Palacio de la Opera de A Coruna (Wikipedia + Commons)
"""

from __future__ import annotations

import os
from typing import Dict, List

NGSI_LD_CONTEXT = "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"

ORION_SERVICE = os.environ.get("ORION_SERVICE", "openiot")
ORION_SERVICE_PATH = os.environ.get("ORION_SERVICE_PATH", "/")

ORION_ENTITY_HEADERS = {
    "Content-Type": "application/json",
    "Accept": "application/ld+json",
    "Link": f'<{NGSI_LD_CONTEXT}>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"',
}
if ORION_SERVICE:
    ORION_ENTITY_HEADERS["Fiware-Service"] = ORION_SERVICE
    ORION_ENTITY_HEADERS["Fiware-ServicePath"] = ORION_SERVICE_PATH

MUSEUMS: List[Dict] = [
    {
        "id": "urn:ngsi-ld:Museum:muncyt-coruna",
        "code": "muncyt",
        "name": "Museo Nacional de Ciencia y Tecnologia (MUNCYT)",
        "alternateName": "MUNCYT Coruna",
        "description": "Sede del Museo Nacional de Ciencia y Tecnologia en A Coruna, ubicada en el edificio Prisma de Cristal.",
        "museumType": ["museum", "science-museum"],
        "address": "Praza do Museo Nacional de Ciencia, 1, 15011 A Coruna",
        "location": {"type": "Point", "coordinates": [-8.4203453, 43.3731638]},
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/A%20Coru%C3%B1a%20-%20Museo%20Nacional%20de%20Ciencia%20y%20Tecnolog%C3%ADa%20%28MUNCYT%29%201.JPG",
        "sourceUrl": "https://www.muncyt.es/sobre-el-museo/sedes/muncyt-coruna",
    },
    {
        "id": "urn:ngsi-ld:Museum:bellas-artes-coruna",
        "code": "bellasartes",
        "name": "Museo de Bellas Artes de A Coruna",
        "alternateName": "Museo de Belas Artes da Coruna",
        "description": "Pinacoteca con colecciones de pintura y escultura entre los siglos XVI y XX, con salas por periodos y colecciones especiales.",
        "museumType": ["museum", "fine-arts-museum"],
        "address": "Rua Zalaeta, 2, 15002 A Coruna",
        "location": {"type": "Point", "coordinates": [-8.3996578, 43.3727883]},
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/A%20Coru%C3%B1a%20-%20Museo%20de%20Bellas%20Artes%201.JPG",
        "sourceUrl": "https://es.wikipedia.org/wiki/Museo_de_Bellas_Artes_de_La_Coru%C3%B1a",
    },
    {
        "id": "urn:ngsi-ld:Museum:teatro-rosalia-castro",
        "code": "rosalia",
        "name": "Teatro Rosalia de Castro",
        "alternateName": "Teatro Municipal Rosalia de Castro",
        "description": "Teatro historico de A Coruna con patio de butacas, anfiteatro, palcos y espacios de escena.",
        "museumType": ["theatre", "performing-arts"],
        "address": "Rua Riego de Agua, 37, 15001 A Coruna",
        "location": {"type": "Point", "coordinates": [-8.3985089, 43.3702205]},
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Teatro%20Rosal%C3%ADa%20de%20Castro%20A%20Coru%C3%B1a.jpg",
        "sourceUrl": "https://es.wikipedia.org/wiki/Teatro_Rosal%C3%ADa_de_Castro_(La_Coru%C3%B1a)",
    },
    {
        "id": "urn:ngsi-ld:Museum:palacio-opera-coruna",
        "code": "opera",
        "name": "Palacio de la Opera",
        "alternateName": "Palacio da Opera da Coruna",
        "description": "Infraestructura cultural multiuso con auditorio principal y salas auxiliares para congresos y artes escenicas.",
        "museumType": ["concert-hall", "theatre", "conference-center"],
        "address": "Glorieta de America, s/n, 15004 A Coruna",
        "location": {"type": "Point", "coordinates": [-8.4109463, 43.3631533]},
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/A%20Coru%C3%B1a%20-%20Palacio%20de%20la%20%C3%93pera%201.JPG",
        "sourceUrl": "https://es.wikipedia.org/wiki/Palacio_de_la_%C3%93pera_(La_Coru%C3%B1a)",
    },
]

ROOMS: List[Dict] = [
    # MUNCYT — interiores reales del museo (Wikimedia Commons, verificados)
    {
        "id": "urn:ngsi-ld:Room:muncyt-piezas-con-memoria",
        "code": "piezas_con_memoria",
        "museumId": "urn:ngsi-ld:Museum:muncyt-coruna",
        "name": "Sala Piezas con Memoria",
        "floor": 0,
        "area": 550,
        "capacity": 140,
        "roomType": "exhibition",
        "description": "Sala tematica de piezas historicas de ciencia y tecnologia.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/6/6a/2760-Boeing_747_%28MUNCYT%29_Coru%C3%B1a.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:muncyt-ex-catedra",
        "code": "ex_catedra",
        "museumId": "urn:ngsi-ld:Museum:muncyt-coruna",
        "name": "Sala Ex Catedra",
        "floor": 1,
        "area": 430,
        "capacity": 110,
        "roomType": "exhibition",
        "description": "Espacio expositivo sobre conocimiento cientifico y educacion.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/5/5f/2761-Boeing_747_%28MUNCYT%29_Coru%C3%B1a.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:muncyt-creadores",
        "code": "creadores",
        "museumId": "urn:ngsi-ld:Museum:muncyt-coruna",
        "name": "Sala Creador.es",
        "floor": 1,
        "area": 390,
        "capacity": 95,
        "roomType": "exhibition",
        "description": "Sala dedicada a innovacion, inventores y procesos tecnicos.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/5/52/2762-Boing_747_%28MUNCYT%29_Coru%C3%B1a..jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:muncyt-miscelanea",
        "code": "miscelanea",
        "museumId": "urn:ngsi-ld:Museum:muncyt-coruna",
        "name": "Sala Miscelanea",
        "floor": 2,
        "area": 320,
        "capacity": 85,
        "roomType": "exhibition",
        "description": "Sala con objetos tecnicos de colecciones mixtas.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/7/70/Lente_de_Fresnel_de_la_Torre_de_H%C3%A9rcules.101_-_MUNCYT.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:muncyt-temporales",
        "code": "temporales",
        "museumId": "urn:ngsi-ld:Museum:muncyt-coruna",
        "name": "Sala de Exposiciones Temporales",
        "floor": 2,
        "area": 360,
        "capacity": 100,
        "roomType": "exhibition",
        "description": "Area para muestras temporales y rotacion de coleccion.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/b/be/Lente_de_Fresnel_de_la_Torre_de_H%C3%A9rcules.002_-_MUNCYT.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:muncyt-salon-de-actos",
        "code": "salon_actos",
        "museumId": "urn:ngsi-ld:Museum:muncyt-coruna",
        "name": "Salon de Actos",
        "floor": 0,
        "area": 240,
        "capacity": 120,
        "roomType": "performance",
        "description": "Salon para actividades divulgativas y eventos educativos.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Interior_Pazo_da_%C3%93pera_da_Coru%C3%B1a.jpg",
    },
    # Bellas Artes — interiores de pinacoteca (Unsplash)
    {
        "id": "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
        "code": "siglos_xvi_xvii",
        "museumId": "urn:ngsi-ld:Museum:bellas-artes-coruna",
        "name": "Sala de Pintura de los Siglos XVI y XVII",
        "floor": 0,
        "area": 310,
        "capacity": 70,
        "roomType": "exhibition",
        "description": "Pintura espanola y europea de los siglos XVI y XVII.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Museo_de_Belas_Artes_da_Coru%C3%B1a_-_Sala_6.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:bellasartes-siglos-xviii-xix",
        "code": "siglos_xviii_xix",
        "museumId": "urn:ngsi-ld:Museum:bellas-artes-coruna",
        "name": "Sala de Pintura de los Siglos XVIII y XIX",
        "floor": 1,
        "area": 300,
        "capacity": 68,
        "roomType": "exhibition",
        "description": "Colecciones neoclasicas y romanticas.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/1/18/Desnudo_de_ni%C3%B1a_con_los_brazos_cruzados_1913_Mar%C3%ADa_Roesset._Museo_de_Belas_Artes_da_Coru%C3%B1a.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:bellasartes-siglo-xx",
        "code": "siglo_xx",
        "museumId": "urn:ngsi-ld:Museum:bellas-artes-coruna",
        "name": "Sala de Pintura del Siglo XX (Sala 6)",
        "floor": 1,
        "area": 290,
        "capacity": 64,
        "roomType": "exhibition",
        "description": "Sala de arte moderno y contemporaneo del museo.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Carrero_Fern%C3%A1ndez%2C_Na_fragua%2C_1890-1902.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:bellasartes-goya",
        "code": "grabados_goya",
        "museumId": "urn:ngsi-ld:Museum:bellas-artes-coruna",
        "name": "Sala de Grabados de Goya",
        "floor": 2,
        "area": 180,
        "capacity": 40,
        "roomType": "exhibition",
        "description": "Espacio para obra grafica y grabado historico.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/d/db/Los_Caprichos%2C_LDUT182%2810%29.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:bellasartes-sargadelos",
        "code": "sargadelos",
        "museumId": "urn:ngsi-ld:Museum:bellas-artes-coruna",
        "name": "Sala de Ceramica de Sargadelos",
        "floor": 2,
        "area": 150,
        "capacity": 35,
        "roomType": "exhibition",
        "description": "Coleccion de loza y ceramica de Sargadelos.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/5/56/Coru%C3%B1a_-_Panorama_-_Museo_Belas_Artes_01.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:bellasartes-temporales",
        "code": "temporales",
        "museumId": "urn:ngsi-ld:Museum:bellas-artes-coruna",
        "name": "Sala de Exposiciones Temporales",
        "floor": 0,
        "area": 220,
        "capacity": 48,
        "roomType": "exhibition",
        "description": "Espacio para muestras temporales y proyectos curatoriales.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/9/98/Ovidio_Murguia_de_Castro_Guadarrama_1898.jpg",
    },
    # Teatro Rosalia — interiores de teatro (Unsplash)
    {
        "id": "urn:ngsi-ld:Room:rosalia-patio-butacas",
        "code": "patio_butacas",
        "museumId": "urn:ngsi-ld:Museum:teatro-rosalia-castro",
        "name": "Patio de Butacas",
        "floor": 0,
        "area": 420,
        "capacity": 360,
        "roomType": "performance",
        "description": "Area principal de publico durante representaciones.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Teatro_Rosal%C3%ADa_de_Castro_A_Coru%C3%B1a.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:rosalia-anfiteatro",
        "code": "anfiteatro",
        "museumId": "urn:ngsi-ld:Museum:teatro-rosalia-castro",
        "name": "Anfiteatro",
        "floor": 1,
        "area": 210,
        "capacity": 150,
        "roomType": "performance",
        "description": "Nivel elevado para vision global del escenario.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/5/53/Porta_Rosalia_de_Castro_da_Coru%C3%B1a.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:rosalia-palcos",
        "code": "palcos",
        "museumId": "urn:ngsi-ld:Museum:teatro-rosalia-castro",
        "name": "Palcos",
        "floor": 2,
        "area": 170,
        "capacity": 90,
        "roomType": "performance",
        "description": "Zona lateral superior de palcos historicos.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Teatro_Rosal%C3%ADa_de_Castro_A_Coru%C3%B1a.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:rosalia-escenario",
        "code": "escenario",
        "museumId": "urn:ngsi-ld:Museum:teatro-rosalia-castro",
        "name": "Escenario Principal",
        "floor": 0,
        "area": 150,
        "capacity": 80,
        "roomType": "performance",
        "description": "Escenario tecnico para funciones teatrales y conciertos.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/9/96/P1330065_Placa_Teatro_Rosal%C3%ADa_de_Castro_na_Coru%C3%B1a.JPG",
    },
    {
        "id": "urn:ngsi-ld:Room:rosalia-foyer",
        "code": "foyer",
        "museumId": "urn:ngsi-ld:Museum:teatro-rosalia-castro",
        "name": "Foyer",
        "floor": 0,
        "area": 190,
        "capacity": 140,
        "roomType": "lobby",
        "description": "Vestibulo principal y zona de recepcion de publico.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/d/db/P1330066_Placa_Teatro_Rosal%C3%ADa_de_Castro_A_Coru%C3%B1a.JPG",
    },
    {
        "id": "urn:ngsi-ld:Room:rosalia-camerinos",
        "code": "camerinos",
        "museumId": "urn:ngsi-ld:Museum:teatro-rosalia-castro",
        "name": "Camerinos",
        "floor": -1,
        "area": 130,
        "capacity": 45,
        "roomType": "storage",
        "description": "Zona de preparacion de elenco y equipos tecnicos.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/6/6a/P1330067_Placa_Teatro_Rosal%C3%ADa_de_Castro_A_Coru%C3%B1a.JPG",
    },
    # Palacio de la Opera — interiores de auditorio y sala de conciertos (Unsplash)
    {
        "id": "urn:ngsi-ld:Room:opera-auditorio-principal",
        "code": "auditorio_principal",
        "museumId": "urn:ngsi-ld:Museum:palacio-opera-coruna",
        "name": "Auditorio Principal",
        "floor": 0,
        "area": 1600,
        "capacity": 1805,
        "roomType": "performance",
        "description": "Sala principal con capacidad para 1805 personas sentadas.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/e/ec/Interior_Pazo_da_%C3%93pera_da_Coru%C3%B1a.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:opera-sala-sonata",
        "code": "sala_sonata",
        "museumId": "urn:ngsi-ld:Museum:palacio-opera-coruna",
        "name": "Sala Sonata",
        "floor": 1,
        "area": 430,
        "capacity": 425,
        "roomType": "performance",
        "description": "Sala de conferencias con escenario para eventos y congresos.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/e/e5/A_Coru%C3%B1a_-_Palacio_de_la_%C3%93pera_1.JPG",
    },
    {
        "id": "urn:ngsi-ld:Room:opera-sala-vivace",
        "code": "sala_vivace",
        "museumId": "urn:ngsi-ld:Museum:palacio-opera-coruna",
        "name": "Sala Vivace",
        "floor": 1,
        "area": 140,
        "capacity": 80,
        "roomType": "performance",
        "description": "Sala auxiliar para reuniones y actos de pequeno formato.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/1/12/A_Coru%C3%B1a_-_Palacio_de_la_%C3%93pera_2.JPG",
    },
    {
        "id": "urn:ngsi-ld:Room:opera-sala-crescendo",
        "code": "sala_crescendo",
        "museumId": "urn:ngsi-ld:Museum:palacio-opera-coruna",
        "name": "Sala Crescendo",
        "floor": 1,
        "area": 120,
        "capacity": 60,
        "roomType": "performance",
        "description": "Sala multiuso para seminarios y formacion.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/8/80/A_Coru%C3%B1a_-_Palacio_de_la_%C3%93pera_3.JPG",
    },
    {
        "id": "urn:ngsi-ld:Room:opera-salon-wengue",
        "code": "salon_wengue",
        "museumId": "urn:ngsi-ld:Museum:palacio-opera-coruna",
        "name": "Salon Wengue",
        "floor": 0,
        "area": 260,
        "capacity": 220,
        "roomType": "lobby",
        "description": "Salon de recepciones de doble altura para eventos institucionales.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/5/58/Palacio_da_%C3%93pera_%28A_Coru%C3%B1a%29.jpg",
    },
    {
        "id": "urn:ngsi-ld:Room:opera-hall-camara",
        "code": "hall_camara",
        "museumId": "urn:ngsi-ld:Museum:palacio-opera-coruna",
        "name": "Hall de Camara",
        "floor": 0,
        "area": 240,
        "capacity": 200,
        "roomType": "lobby",
        "description": "Hall asociado a salas de camara y circulacion de publico.",
        "image": "https://upload.wikimedia.org/wikipedia/commons/3/3f/Palacio_da_%C3%B3pera%2C_A_Coru%C3%B1a.JPG",
    },
]

DEVICE_MODELS: List[Dict] = [
    {
        "id": "urn:ngsi-ld:DeviceModel:env-th-sensor-v1",
        "name": "EnviroTH Pro V1",
        "manufacturerName": "SenseCraft",
        "brandName": "SenseCraft",
        "modelName": "TH-2100",
        "category": "sensor",
        "deviceCategory": "temperature-humidity",
        "controlledProperty": ["temperature", "relativeHumidity", "illuminance"],
        "supportedUnits": ["degC", "%", "lux"],
        "supportedProtocol": ["MQTT", "HTTP"],
        "documentation": "https://example.org/devices/enviroth-pro-v1",
    },
    {
        "id": "urn:ngsi-ld:DeviceModel:co2-sensor-v2",
        "name": "AirGuard CO2 V2",
        "manufacturerName": "AirGuard",
        "brandName": "AirGuard",
        "modelName": "CO2-880",
        "category": "sensor",
        "deviceCategory": "co2",
        "controlledProperty": ["co2", "temperature"],
        "supportedUnits": ["ppm", "degC"],
        "supportedProtocol": ["MQTT"],
        "documentation": "https://example.org/devices/airguard-co2-v2",
    },
    {
        "id": "urn:ngsi-ld:DeviceModel:sound-meter-v1",
        "name": "Acoustic SLM 1",
        "manufacturerName": "AcoustiLab",
        "brandName": "AcoustiLab",
        "modelName": "SLM-A",
        "category": "sensor",
        "deviceCategory": "noise",
        "controlledProperty": ["LAeq", "LAmax", "LAS"],
        "supportedUnits": ["dB(A)"],
        "supportedProtocol": ["MQTT"],
        "documentation": "https://example.org/devices/acoustic-slm-1",
    },
    {
        "id": "urn:ngsi-ld:DeviceModel:crowd-sensor-v3",
        "name": "CrowdSense Vision V3",
        "manufacturerName": "FlowMetrics",
        "brandName": "FlowMetrics",
        "modelName": "CF-500",
        "category": "sensor",
        "deviceCategory": "occupancy",
        "controlledProperty": ["peopleCount", "occupancy", "direction"],
        "supportedUnits": ["people", "ratio"],
        "supportedProtocol": ["MQTT"],
        "documentation": "https://example.org/devices/crowdsense-v3",
    },
    {
        "id": "urn:ngsi-ld:DeviceModel:hvac-controller-v1",
        "name": "HVAC Control Hub",
        "manufacturerName": "ClimaCore",
        "brandName": "ClimaCore",
        "modelName": "HVAC-CTRL-1",
        "category": "actuator-controller",
        "deviceCategory": "hvac",
        "controlledProperty": ["temperature", "co2", "relativeHumidity"],
        "supportedUnits": ["state", "ratio"],
        "supportedProtocol": ["MQTT", "HTTP"],
        "documentation": "https://example.org/devices/hvac-control-hub",
    },
]

ARTWORKS: List[Dict] = [
    # MUNCYT (coleccion real documentada en CERES / Wikimedia)
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-abarth-1000",
        "name": "Automovil Abarth 1000",
        "artist": "Abarth & C.",
        "year": 1968,
        "material": "metal-fiberglass",
        "technique": "manufactura industrial",
        "origin": "Bolonia, Italia",
        "roomId": "urn:ngsi-ld:Room:muncyt-miscelanea",
        "image": "https://ceres.mcu.es/pages/Viewer?img=/MUNCYT/fondos_sello/MUNCYTMFCE1983_002_0069_SEQ_118_S.JPG",
        "sourceUrl": "https://ceres.mcu.es/pages/SpecialMuseumSearch?Access=MUNCYT",
        "conservationRequirements": {
            "temperatureMin": 16,
            "temperatureMax": 24,
            "humidityMin": 35,
            "humidityMax": 55,
            "co2Max": 1200,
            "illuminanceMax": 300,
            "noiseMax": 75,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-astrolabio-1630",
        "name": "Astrolabio",
        "artist": "Autor desconocido",
        "year": 1630,
        "material": "metal-madera-papel",
        "technique": "instrumentacion cientifica",
        "origin": "Madrid, Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-ex-catedra",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Astrolabio%201630%20MUNCYT.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museo_Nacional_de_Ciencia_y_Tecnolog%C3%ADa",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 40,
            "humidityMax": 55,
            "co2Max": 1000,
            "illuminanceMax": 120,
            "noiseMax": 65,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-planisferio-celeste-1634",
        "name": "Planisferio Celeste",
        "artist": "Claude Richard",
        "year": 1634,
        "material": "carton-madera-metal",
        "technique": "grabado cientifico",
        "origin": "Madrid, Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-ex-catedra",
        "image": "https://ceres.mcu.es/pages/Viewer?img=/MUNCYT/fondos_sello/MUNCYTMFCE1985_004_0365_SEQ_017_S.JPG",
        "sourceUrl": "https://ceres.mcu.es/pages/SpecialMuseumSearch?Access=MUNCYT",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 21,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 80,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-planisferio-terrestre-1634",
        "name": "Planisferio Terrestre",
        "artist": "Claude Richard",
        "year": 1634,
        "material": "carton-madera-metal",
        "technique": "grabado cientifico",
        "origin": "Madrid, Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-ex-catedra",
        "image": "https://ceres.mcu.es/pages/Viewer?img=/MUNCYT/fondos_sello/MUNCYTMFCE1985_004_0366_SEQ_016_S.JPG",
        "sourceUrl": "https://ceres.mcu.es/pages/SpecialMuseumSearch?Access=MUNCYT",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 21,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 80,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-pila-electrica",
        "name": "Pila Electrica",
        "artist": "Autor desconocido",
        "year": 1840,
        "material": "metal-vidrio-madera",
        "technique": "instrumentacion cientifica",
        "origin": "Madrid, Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-piezas-con-memoria",
        "image": "https://ceres.mcu.es/pages/Viewer?img=/MUNCYT/fondos_sello/MUNCYTMFCE1985_004_0434_SEQ_009_S.JPG",
        "sourceUrl": "https://ceres.mcu.es/pages/SpecialMuseumSearch?Access=MUNCYT",
        "conservationRequirements": {
            "temperatureMin": 17,
            "temperatureMax": 23,
            "humidityMin": 35,
            "humidityMax": 55,
            "co2Max": 1200,
            "illuminanceMax": 200,
            "noiseMax": 70,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-pila-clamond",
        "name": "Pila Termoelectrica de Clamond",
        "artist": "Autor desconocido",
        "year": 1900,
        "material": "metal-amianto",
        "technique": "instrumentacion cientifica",
        "origin": "Madrid, Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-piezas-con-memoria",
        "image": "https://ceres.mcu.es/pages/Viewer?img=/MUNCYT/fondos_sello/MUNCYTMFCE1985_004_0436_SEQ_001_S.JPG",
        "sourceUrl": "https://ceres.mcu.es/pages/SpecialMuseumSearch?Access=MUNCYT",
        "conservationRequirements": {
            "temperatureMin": 17,
            "temperatureMax": 24,
            "humidityMin": 35,
            "humidityMax": 55,
            "co2Max": 1200,
            "illuminanceMax": 220,
            "noiseMax": 72,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-rueda-traccion-humana",
        "name": "Modelo de Rueda de Traccion Humana",
        "artist": "Breton Freres",
        "year": 1850,
        "material": "madera-acero",
        "technique": "maqueta mecanica",
        "origin": "Paris, Francia",
        "roomId": "urn:ngsi-ld:Room:muncyt-piezas-con-memoria",
        "image": "https://ceres.mcu.es/pages/Viewer?img=/MUNCYT/fondos_sello/MUNCYTMFCE1985_004_0041_SEQ_005_S.JPG",
        "sourceUrl": "https://ceres.mcu.es/pages/SpecialMuseumSearch?Access=MUNCYT",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 23,
            "humidityMin": 40,
            "humidityMax": 55,
            "co2Max": 1100,
            "illuminanceMax": 150,
            "noiseMax": 68,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-aparato-kipp",
        "name": "Aparato de Kipp",
        "artist": "Autor desconocido",
        "year": 1890,
        "material": "vidrio",
        "technique": "soplado de vidrio cientifico",
        "origin": "Antequera, Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-piezas-con-memoria",
        "image": "https://ceres.mcu.es/pages/Viewer?img=/MUNCYT/fondos_sello/MUNCYTMFCE1984_004_0048_SEQ_004_S.JPG",
        "sourceUrl": "https://ceres.mcu.es/pages/SpecialMuseumSearch?Access=MUNCYT",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 1000,
            "illuminanceMax": 120,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-ibm650",
        "name": "Ordenador IBM 650",
        "artist": "IBM",
        "year": 1959,
        "material": "metal-electronica",
        "technique": "computacion electromecanica",
        "origin": "Estados Unidos",
        "roomId": "urn:ngsi-ld:Room:muncyt-creadores",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Ordenador%20IBM650%201959%20MUNCYT.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Museo_Nacional_de_Ciencia_y_Tecnolog%C3%ADa",
        "conservationRequirements": {
            "temperatureMin": 17,
            "temperatureMax": 23,
            "humidityMin": 35,
            "humidityMax": 50,
            "co2Max": 1200,
            "illuminanceMax": 180,
            "noiseMax": 70,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-seat-600",
        "name": "SEAT 600 D",
        "artist": "SEAT",
        "year": 1965,
        "material": "metal-vidrio-caucho",
        "technique": "automocion industrial",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-miscelanea",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/SEAT%20600%20D%20%281965%29.001%20-%20MUNCYT.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museo_Nacional_de_Ciencia_y_Tecnolog%C3%ADa_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 15,
            "temperatureMax": 25,
            "humidityMin": 35,
            "humidityMax": 60,
            "co2Max": 1400,
            "illuminanceMax": 320,
            "noiseMax": 78,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-traje-estratosferico",
        "name": "Reproduccion del Traje Estratosferico de Emilio Herrera",
        "artist": "Emilio Herrera Linares",
        "year": 1935,
        "material": "tejido-metal-caucho",
        "technique": "ingenieria aeroespacial",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-temporales",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Reproducci%C3%B3n%20del%20traje%20estratosf%C3%A9rico%20de%20Emilio%20Herrera%20Linares.001%20-%20MUNCYT.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museo_Nacional_de_Ciencia_y_Tecnolog%C3%ADa_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 40,
            "humidityMax": 55,
            "co2Max": 1000,
            "illuminanceMax": 120,
            "noiseMax": 65,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-microscopio-electronico",
        "name": "Microscopio Electronico",
        "artist": "Autor desconocido",
        "year": 1960,
        "material": "metal-electronica",
        "technique": "instrumentacion de laboratorio",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-creadores",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Microscopio%20Electr%C3%B3nico%201960.JPG",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museo_Nacional_de_Ciencia_y_Tecnolog%C3%ADa",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 23,
            "humidityMin": 35,
            "humidityMax": 50,
            "co2Max": 1100,
            "illuminanceMax": 180,
            "noiseMax": 68,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-marcapasos-1975",
        "name": "Marcapasos",
        "artist": "Autor desconocido",
        "year": 1975,
        "material": "metal-electronica-polimero",
        "technique": "ingenieria biomedica",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-creadores",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Marcapasos%20%281975%29.001%20-%20MUNCYT.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museo_Nacional_de_Ciencia_y_Tecnolog%C3%ADa_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 23,
            "humidityMin": 35,
            "humidityMax": 50,
            "co2Max": 1100,
            "illuminanceMax": 160,
            "noiseMax": 66,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-proyector-peliculas",
        "name": "Proyector de Peliculas",
        "artist": "Autor desconocido",
        "year": 1930,
        "material": "metal-vidrio",
        "technique": "proyeccion cinematografica",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:muncyt-temporales",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Proyector%20de%20pel%C3%ADculas.001%20-%20MUNCYT.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Collections_of_the_Museo_Nacional_de_Ciencia_y_Tecnolog%C3%ADa_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 23,
            "humidityMin": 35,
            "humidityMax": 55,
            "co2Max": 1150,
            "illuminanceMax": 200,
            "noiseMax": 70,
        },
    },
    # Bellas Artes (coleccion y pinturas documentadas en Commons)
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-arrepentimiento-san-pedro",
        "name": "Arrepentimiento de San Pedro",
        "artist": "Francisco Collantes",
        "year": 1640,
        "material": "oil-on-canvas",
        "technique": "pintura barroca",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Arrepentimiento%20de%20San%20Pedro%2C%20de%20Francisco%20Collantes%20%28Museo%20de%20Bellas%20Artes%20de%20La%20Coru%C3%B1a%29.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 150,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-cristo-cruz",
        "name": "Cristo en la Cruz",
        "artist": "Autor anonimo",
        "year": 1600,
        "material": "oil-on-canvas",
        "technique": "pintura religiosa",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Cristo%20en%20la%20Cruz%20%28Museo%20de%20Bellas%20Artes%20de%20La%20Coru%C3%B1a%29.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 140,
            "noiseMax": 58,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-ecce-homo",
        "name": "Ecce Homo",
        "artist": "Atribuido a Luis de Morales",
        "year": 1560,
        "material": "oil-on-panel",
        "technique": "pintura renacentista",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Ecce%20Homo%2C%20atribuido%20a%20Luis%20de%20Morales%20%28Museo%20de%20Bellas%20Artes%20de%20La%20Coru%C3%B1a%29.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 120,
            "noiseMax": 58,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-sagrada-familia",
        "name": "La Sagrada Familia",
        "artist": "Juan de Juanes",
        "year": 1565,
        "material": "oil-on-panel",
        "technique": "pintura religiosa",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/La%20Sagrada%20Familia%2C%20de%20Juan%20de%20Juanes%20%28Museo%20de%20Bellas%20Artes%20de%20La%20Coru%C3%B1a%29.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 130,
            "noiseMax": 58,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-desnudo-nina",
        "name": "Desnudo de nina con los brazos cruzados",
        "artist": "Maria Roesset",
        "year": 1913,
        "material": "oil-on-canvas",
        "technique": "pintura modernista",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglo-xx",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Desnudo%20de%20ni%C3%B1a%20con%20los%20brazos%20cruzados%201913%20Mar%C3%ADa%20Roesset.%20Museo%20de%20Belas%20Artes%20da%20Coru%C3%B1a.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 950,
            "illuminanceMax": 150,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-aldea-gallega",
        "name": "Aldea gallega",
        "artist": "Serafin Avendano",
        "year": 1908,
        "material": "oil-on-canvas",
        "technique": "paisajismo",
        "origin": "Galicia, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglo-xx",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Seraf%C3%ADn%20Avenda%C3%B1o%20ca%201908%20Aldea%20gallega.%20Museo%20de%20Belas%20Artes%20da%20Coru%C3%B1a.JPG",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 950,
            "illuminanceMax": 150,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-apoteosis-hercules",
        "name": "The Apotheosis of Hercules",
        "artist": "Jan Baptist Borrekens (after Rubens)",
        "year": 1650,
        "material": "oil-on-canvas",
        "technique": "baroque painting",
        "origin": "Flanders",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Jan%20Baptist%20Borrekens%2C%20after%20Rubens%20-%20The%20apotheosis%20of%20Hercules.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 140,
            "noiseMax": 58,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-ovidio-guadarrama",
        "name": "Guadarrama",
        "artist": "Ovidio Murguia de Castro",
        "year": 1898,
        "material": "oil-on-canvas",
        "technique": "paisajismo",
        "origin": "Galicia, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglos-xviii-xix",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Ovidio%20Murguia%20de%20Castro%20Guadarrama%201898.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 950,
            "illuminanceMax": 150,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-na-fragua",
        "name": "Na Fragua",
        "artist": "Jenaro Carrero Fernandez",
        "year": 1900,
        "material": "oil-on-canvas",
        "technique": "costumbrismo",
        "origin": "Galicia, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglo-xx",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Carrero%20Fern%C3%A1ndez%2C%20Na%20fragua%2C%201890-1902.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 950,
            "illuminanceMax": 150,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-jugadores-cartas",
        "name": "Jugadores de cartas",
        "artist": "Theodoor Rombouts",
        "year": 1630,
        "material": "oil-on-canvas",
        "technique": "pintura barroca",
        "origin": "Antwerp, Flanders",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
        "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Rombouts-jugadores%20de%20cartas.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Paintings_in_the_Museo_de_Belas_Artes_da_Coru%C3%B1a",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 140,
            "noiseMax": 58,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:muncyt-lente-fresnel",
        "name": "Lente de Fresnel del Faro de Estaca de Bares",
        "artist": "Sautter & Cie",
        "year": 1847,
        "material": "vidrio-metal",
        "technique": "optica",
        "origin": "Paris, Francia",
        "roomId": "urn:ngsi-ld:Room:muncyt-miscelanea",
        "image": "https://upload.wikimedia.org/wikipedia/commons/b/be/Lente_de_Fresnel_de_la_Torre_de_H%C3%A9rcules.002_-_MUNCYT.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lente_de_Fresnel_de_la_Torre_de_H%C3%A9rcules.002_-_MUNCYT.jpg",
        "conservationRequirements": {
            "temperatureMin": 15,
            "temperatureMax": 25,
            "humidityMin": 30,
            "humidityMax": 60,
            "co2Max": 1000,
            "illuminanceMax": 300,
            "noiseMax": 70,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-goya-caprichos",
        "name": "Los Caprichos: El sueno de la razon produce monstruos",
        "artist": "Francisco de Goya",
        "year": 1799,
        "material": "papel",
        "technique": "aguafuerte",
        "origin": "Madrid, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-goya",
        "image": "https://upload.wikimedia.org/wikipedia/commons/d/db/Los_Caprichos%2C_LDUT182%2810%29.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Los_Caprichos,_LDUT182(10).jpg",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 21,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 800,
            "illuminanceMax": 50,
            "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-modesto-brocos",
        "name": "El Muneco",
        "artist": "Modesto Brocos",
        "year": 1880,
        "material": "oil-on-canvas",
        "technique": "pintura",
        "origin": "Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-siglos-xviii-xix",
        "image": "https://upload.wikimedia.org/wikipedia/commons/2/20/Modesto_Brocos_y_Gomes_-_Camponesa.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Modesto_Brocos",
        "conservationRequirements": {
            "temperatureMin": 18,
            "temperatureMax": 22,
            "humidityMin": 45,
            "humidityMax": 55,
            "co2Max": 900,
            "illuminanceMax": 150,
            "noiseMax": 60,
        },
    },
    # Sala Ceramica de Sargadelos
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-sargadelos-tetera-gondola",
        "name": "Tetera de la Serie Gondola",
        "artist": "Real Fabrica de Sargadelos",
        "year": 1845,
        "material": "loza-esmalte",
        "technique": "ceramica vidriada con decoracion transferida",
        "origin": "O Vicedo, Lugo, Galicia, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-sargadelos",
        "image": "https://upload.wikimedia.org/wikipedia/commons/5/56/Coru%C3%B1a_-_Panorama_-_Museo_Belas_Artes_01.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Sargadelos",
        "conservationRequirements": {
            "temperatureMin": 17, "temperatureMax": 23,
            "humidityMin": 40, "humidityMax": 58,
            "co2Max": 1000, "illuminanceMax": 200, "noiseMax": 62,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-sargadelos-plato-flora",
        "name": "Plato Decorativo de la Serie Flora",
        "artist": "Real Fabrica de Sargadelos",
        "year": 1860,
        "material": "loza-esmalte",
        "technique": "ceramica estampada en azul cobalto",
        "origin": "O Vicedo, Lugo, Galicia, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-sargadelos",
        "image": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Museo_de_Belas_Artes_da_Coru%C3%B1a_-_Sala_6.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Sargadelos",
        "conservationRequirements": {
            "temperatureMin": 17, "temperatureMax": 23,
            "humidityMin": 40, "humidityMax": 58,
            "co2Max": 1000, "illuminanceMax": 200, "noiseMax": 62,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-sargadelos-figura-gaiteiro",
        "name": "Figura de Gaiteiro (Muneco Tradicional de Sargadelos)",
        "artist": "Real Fabrica de Sargadelos",
        "year": 1885,
        "material": "porcelana-esmalte",
        "technique": "moldeo y esmaltado artesanal",
        "origin": "O Vicedo, Lugo, Galicia, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-sargadelos",
        "image": "https://upload.wikimedia.org/wikipedia/commons/2/20/Modesto_Brocos_y_Gomes_-_Camponesa.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Sargadelos",
        "conservationRequirements": {
            "temperatureMin": 16, "temperatureMax": 22,
            "humidityMin": 42, "humidityMax": 58,
            "co2Max": 950, "illuminanceMax": 180, "noiseMax": 60,
        },
    },
    # Sala Exposiciones Temporales — Bellas Artes
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-temporales-goya-disparate",
        "name": "Disparate Claro (No. 18 de los Disparates)",
        "artist": "Francisco de Goya",
        "year": 1816,
        "material": "papel",
        "technique": "aguatinta y aguafuerte",
        "origin": "Madrid, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-temporales",
        "image": "https://upload.wikimedia.org/wikipedia/commons/1/1f/Los_Caprichos%2C_LDUT182%2811%29.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Prints_by_Francisco_Goya",
        "conservationRequirements": {
            "temperatureMin": 18, "temperatureMax": 21,
            "humidityMin": 45, "humidityMax": 54,
            "co2Max": 800, "illuminanceMax": 50, "noiseMax": 58,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-temporales-san-sebastian-barroco",
        "name": "San Sebastian (Pintura Barroca Flamenca)",
        "artist": "Cornelis de Vos (attr.)",
        "year": 1625,
        "material": "oil-on-canvas",
        "technique": "pintura barroca flamenca",
        "origin": "Amberes, Flandes",
        "roomId": "urn:ngsi-ld:Room:bellasartes-temporales",
        "image": "https://upload.wikimedia.org/wikipedia/commons/9/98/Ovidio_Murguia_de_Castro_Guadarrama_1898.jpg",
        "sourceUrl": "https://commons.wikimedia.org/wiki/Category:Cornelis_de_Vos",
        "conservationRequirements": {
            "temperatureMin": 18, "temperatureMax": 22,
            "humidityMin": 45, "humidityMax": 55,
            "co2Max": 900, "illuminanceMax": 150, "noiseMax": 60,
        },
    },
    {
        "id": "urn:ngsi-ld:Artwork:bellasartes-temporales-asorey-figura",
        "name": "Figura Femenina con Cantaro (Escultura en Bronce)",
        "artist": "Francisco Asorey",
        "year": 1928,
        "material": "bronze",
        "technique": "fundicion a la cera perdida",
        "origin": "Cambados, Galicia, Espana",
        "roomId": "urn:ngsi-ld:Room:bellasartes-temporales",
        "image": "https://upload.wikimedia.org/wikipedia/commons/9/9e/Carrero_Fern%C3%A1ndez%2C_Na_fragua%2C_1890-1902.jpg",
        "sourceUrl": "https://es.wikipedia.org/wiki/Francisco_Asorey",
        "conservationRequirements": {
            "temperatureMin": 16, "temperatureMax": 24,
            "humidityMin": 35, "humidityMax": 55,
            "co2Max": 1000, "illuminanceMax": 300, "noiseMax": 65,
        },
    },
]

MUSEUM_ROOM_MAP: Dict[str, List[Dict]] = {}
for room in ROOMS:
    MUSEUM_ROOM_MAP.setdefault(room["museumId"], []).append(room)

ROOM_NEIGHBORS: Dict[str, List[str]] = {
    # MUNCYT
    "urn:ngsi-ld:Room:muncyt-piezas-con-memoria": [
        "urn:ngsi-ld:Room:muncyt-ex-catedra",
        "urn:ngsi-ld:Room:muncyt-salon-de-actos",
    ],
    "urn:ngsi-ld:Room:muncyt-ex-catedra": [
        "urn:ngsi-ld:Room:muncyt-piezas-con-memoria",
        "urn:ngsi-ld:Room:muncyt-creadores",
    ],
    "urn:ngsi-ld:Room:muncyt-creadores": [
        "urn:ngsi-ld:Room:muncyt-ex-catedra",
        "urn:ngsi-ld:Room:muncyt-miscelanea",
    ],
    "urn:ngsi-ld:Room:muncyt-miscelanea": [
        "urn:ngsi-ld:Room:muncyt-creadores",
        "urn:ngsi-ld:Room:muncyt-temporales",
    ],
    "urn:ngsi-ld:Room:muncyt-temporales": [
        "urn:ngsi-ld:Room:muncyt-miscelanea",
        "urn:ngsi-ld:Room:muncyt-salon-de-actos",
    ],
    "urn:ngsi-ld:Room:muncyt-salon-de-actos": [
        "urn:ngsi-ld:Room:muncyt-piezas-con-memoria",
        "urn:ngsi-ld:Room:muncyt-temporales",
    ],
    # Bellas
    "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii": [
        "urn:ngsi-ld:Room:bellasartes-siglos-xviii-xix",
        "urn:ngsi-ld:Room:bellasartes-goya",
    ],
    "urn:ngsi-ld:Room:bellasartes-siglos-xviii-xix": [
        "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
        "urn:ngsi-ld:Room:bellasartes-siglo-xx",
    ],
    "urn:ngsi-ld:Room:bellasartes-siglo-xx": [
        "urn:ngsi-ld:Room:bellasartes-siglos-xviii-xix",
        "urn:ngsi-ld:Room:bellasartes-temporales",
    ],
    "urn:ngsi-ld:Room:bellasartes-goya": [
        "urn:ngsi-ld:Room:bellasartes-sargadelos",
        "urn:ngsi-ld:Room:bellasartes-siglos-xvi-xvii",
    ],
    "urn:ngsi-ld:Room:bellasartes-sargadelos": [
        "urn:ngsi-ld:Room:bellasartes-goya",
        "urn:ngsi-ld:Room:bellasartes-temporales",
    ],
    "urn:ngsi-ld:Room:bellasartes-temporales": [
        "urn:ngsi-ld:Room:bellasartes-siglo-xx",
        "urn:ngsi-ld:Room:bellasartes-sargadelos",
    ],
    # Rosalia
    "urn:ngsi-ld:Room:rosalia-patio-butacas": [
        "urn:ngsi-ld:Room:rosalia-anfiteatro",
        "urn:ngsi-ld:Room:rosalia-foyer",
    ],
    "urn:ngsi-ld:Room:rosalia-anfiteatro": [
        "urn:ngsi-ld:Room:rosalia-patio-butacas",
        "urn:ngsi-ld:Room:rosalia-palcos",
    ],
    "urn:ngsi-ld:Room:rosalia-palcos": [
        "urn:ngsi-ld:Room:rosalia-anfiteatro",
        "urn:ngsi-ld:Room:rosalia-escenario",
    ],
    "urn:ngsi-ld:Room:rosalia-escenario": [
        "urn:ngsi-ld:Room:rosalia-patio-butacas",
        "urn:ngsi-ld:Room:rosalia-camerinos",
    ],
    "urn:ngsi-ld:Room:rosalia-foyer": [
        "urn:ngsi-ld:Room:rosalia-patio-butacas",
        "urn:ngsi-ld:Room:rosalia-camerinos",
    ],
    "urn:ngsi-ld:Room:rosalia-camerinos": [
        "urn:ngsi-ld:Room:rosalia-escenario",
        "urn:ngsi-ld:Room:rosalia-foyer",
    ],
    # Opera
    "urn:ngsi-ld:Room:opera-auditorio-principal": [
        "urn:ngsi-ld:Room:opera-hall-camara",
        "urn:ngsi-ld:Room:opera-sala-sonata",
    ],
    "urn:ngsi-ld:Room:opera-sala-sonata": [
        "urn:ngsi-ld:Room:opera-auditorio-principal",
        "urn:ngsi-ld:Room:opera-sala-vivace",
    ],
    "urn:ngsi-ld:Room:opera-sala-vivace": [
        "urn:ngsi-ld:Room:opera-sala-sonata",
        "urn:ngsi-ld:Room:opera-sala-crescendo",
    ],
    "urn:ngsi-ld:Room:opera-sala-crescendo": [
        "urn:ngsi-ld:Room:opera-sala-vivace",
        "urn:ngsi-ld:Room:opera-salon-wengue",
    ],
    "urn:ngsi-ld:Room:opera-salon-wengue": [
        "urn:ngsi-ld:Room:opera-hall-camara",
        "urn:ngsi-ld:Room:opera-sala-crescendo",
    ],
    "urn:ngsi-ld:Room:opera-hall-camara": [
        "urn:ngsi-ld:Room:opera-auditorio-principal",
        "urn:ngsi-ld:Room:opera-salon-wengue",
    ],
}


def get_museum(room: Dict) -> Dict:
    museum_id = room["museumId"]
    for museum in MUSEUMS:
        if museum["id"] == museum_id:
            return museum
    raise KeyError(f"Museum not found for room {room['id']}")


def room_location(room: Dict) -> Dict:
    """Crea una ubicacion aproximada por sala basada en coordenadas del centro."""
    museum = get_museum(room)
    base_lon, base_lat = museum["location"]["coordinates"]
    token = sum(ord(c) for c in room["id"]) % 100
    offset_lon = ((token % 10) - 5) * 0.00003
    offset_lat = ((token // 10) - 5) * 0.00003
    return {
        "type": "Point",
        "coordinates": [round(base_lon + offset_lon, 7), round(base_lat + offset_lat, 7)],
    }


def room_code(room_id: str) -> str:
    return room_id.split(":")[-1]
